version: "3"
services:
  user-setting:
    container_name: loan-notification-user-setting
    build:
      context: services/user-setting
      dockerfile: ./Dockerfile
    restart: "on-failure"
    env_file:
      - services/user-setting/.env
    depends_on:
      - kafka

  zookeeper:
    container_name: loan-notification-zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    logging:
      driver: none

  kafka:
    container_name: loan-notification-kafka
    image: wurstmeister/kafka:2.13-2.8.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: host.docker.internal
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "loan-notification-alert-event-v1:1:1"
    depends_on:
      - zookeeper
    logging:
      driver: none
